### ISSUE TITLE
General.explore instead of explore etc

### ISSUE THREAD

**Issue by lentas1** [scratchfoundation/scratch-www#7585]
npm start gets this view to browser
![image](https://user-images.githubusercontent.com/88710364/236749359-28b6f699-c815-4488-b48e-58c91db99a14.png)

### Steps to Reproduce
npm start

### Operating System and Browser

Opera, Win 11

**Comment by lentas1** [comment]
sorry for bad english

**Comment by mxmou** [comment]
I think you need to run `npm run translate` first.

**Comment by lentas1** [comment]
ok

**Comment by lentas1** [comment]
but sign in not working
