### ISSUE TITLE
Use actual copyleft sign on project pages

### ISSUE THREAD

**Issue by Secret-chest** [scratchfoundation/scratch-www#7603]
Right now you use `©` and flip it using CSS, `🄯` should be used instead.

**Comment by mybearworld** [comment]
🄯 is not supported on many systems (Edge & Windows 11, for instance). If this is for accessibility concerns, then a flipped copyright sign with `role=presentation` should still be there.

**Comment by lankybox02** [comment]
![image](https://github.com/scratchfoundation/scratch-www/assets/104015308/c9bac570-3c2e-4aa4-8f6c-7eb289b44b3c)

**Comment by Secret-chest** [comment]
I use Linux and I had it because Mint and the DejaVu fonts. Should I close it? I'm not sure if Windows would support it in 5 years.
