### ISSUE TITLE
Credits page: Call_Me_J_Money and delasare's names are mistakenly usernames

### ISSUE THREAD

**Issue by jeffalo** [scratchfoundation/scratch-www#7604]
On the credits page, Call_Me_J_Money (Jessica) and delasare (Ronald) are credited under their Scratch usernames, and linked to under their real names. That's backwards from everyone else, and means the links go to the wrong places (/users/Jessica and /users/Ronald).

![image](https://github.com/scratchfoundation/scratch-www/assets/40470736/e6a74e2c-293f-42ae-b42b-4584d86eedb2)
![image](https://github.com/scratchfoundation/scratch-www/assets/40470736/e049602c-1116-4623-afae-3575cbb08a9f)

**Comment by Roblox888i** [comment]
This is weird...

**Comment by jeffalo** [comment]
Resolved by #7648
