### ISSUE TITLE
Comments having a lot of issues

### ISSUE THREAD

**Issue by mybearworld** [scratchfoundation/scratch-www#7622]
### Expected Behavior

Comments work as normally, with no CSS issues and no freezing and crashing the page.

### Actual Behavior

Comments will have the minimum width required (even if that goes off screen) and the username not appearing, and inconsistent margins. This is not always the case, though - the issues are seemingly randomly mixed and matched. Sometimes the issues change on hover and also selection with dev tools.

Comment pages load for a bit with every comment already rendered, freezing the site. This also happens on reply and other circumstances I am not sure about. Sometimes the site is also crashed.

The console shows no errors, though.

### Steps to Reproduce

1. Go to any scratch-www page with comments.
2. Try to use it (hover over comments, reply, etc)

### System Details
Windows 11, Microsoft Edge 115.0.1866.1 (Official build) dev (64-bit) 

**Screenshots**

_The comments not having full width, along with the username not appearing_
![The comments not having full width, along with the username not appearing](https://github.com/scratchfoundation/scratch-www/assets/130385691/35a87014-4e6f-4ea6-8ab0-9b36fffaa026)

_The comments not having full width, usernames not appearing, and too much margin_
![The comments not having full width, usernames not appearing, and too much margin](https://github.com/scratchfoundation/scratch-www/assets/130385691/e7fee8fc-cace-4efa-89bc-c4cea8d247f0)

_The comments inconsistently not having full width_
![The comments inconsistently not having full width](https://github.com/scratchfoundation/scratch-www/assets/130385691/90f5fd49-9098-425b-a3d0-51f812782784)

_A comment so long it goes off screen because of the maximum length issue_
![A comment so long it goes off screen because of the maximum length issue](https://github.com/scratchfoundation/scratch-www/assets/130385691/a076adeb-296b-48b2-a9eb-09fcafdd68e6)

_Four of these comments in a row_
![Four of these comments in a row](https://github.com/scratchfoundation/scratch-www/assets/130385691/c82a3c24-ac0b-4e58-9f17-c989374bf88b)

_The site crashing_
![The site crashing](https://github.com/scratchfoundation/scratch-www/assets/130385691/bcfe1d99-b37f-4f6b-96b8-2c5065854b61)

_Not shown: Dev tools hover, initial page hanging_

https://github.com/scratchfoundation/scratch-www/assets/130385691/c39e798c-ec99-44f9-aecf-cbaa033d701d

**Comment by mxmou** [comment]
This seems to be a bug in Edge 115, unrelated to Scratch.

**Comment by mybearworld** [comment]
That seems to be the case.
