### ISSUE TITLE
Add a link redirecting to appeals.scratch.mit.edu for Contact Us

### ISSUE THREAD

**Issue by LuigiUI238** [scratchfoundation/scratch-www#7949]
Make appeals.scratchmit.edu the primary link to Contact Us - This would go in Contact Us on the side of the "Where to get help" section of the Contact Us page.

_Please describe what should happen_  - When a user needs to appeal for a ban, for example, they have two options to appeal from contact us only.

They can contact ST from the [Contact Us](https://scratch.mit.edu/contact-us/) form by explaining what they did and more additional information (already in place)
They can contact ST by email via @appeals@scratch.mit.edu to appeal from their email and service provider website.

This will need to be implemented because users reply from Contact Us and rely on the messages more, but never really receive a response after a month or so.

### Actual Behavior - It redirects users to the Contact Us @appeals.scratch.mit.edu appeal email.

_Describe what happens_ - When clicked, the link will redirect the user to the appeals email by URL pop-up as intended.

### Steps to Reproduce - Easy fix and thing to implement. Just add it as a scratch link to the Contact Us page and that's it.

_Explain what someone needs to do to see what's described in *Actual behavior* above_ - Click on the link and they will be re-directed to their original or default emailing service.

Steps to access the behavior:
1. Go to 'https:/gmail.com/appeals.scratch.mit.edu./...' (or other service providers for your email.)
2. Click on 'Contact by email instead.'
3. Send an appeal about what your going to send to ST.
4. Click "Send" normally.

**Comment by s-aarchen** [comment]
hey, how do I even deploy it? I want to make an alternative scratch platform but I have no experience at all.

**Comment by LuigiUI238** [comment]
> hey, how do I even deploy it? I want to make an alternative scratch platform but I have no experience at all.

I'm not sure what you mean. The link isn't implemented as far as I know.

**Comment by PaperMarioFan-2022** [comment]
I feel like I should close this.
