### ISSUE TITLE
Reduce HTTP Website Requests (Forum and Main Website).

### ISSUE THREAD

**Issue by PaperMarioFan-2022** [scratchfoundation/scratch-www#8600]
### Describe the problem. 
I recall there being problems with requests on the main website and forum structure that is formed and made by ScratchDB, which hasn't been doing very well with handling requests. The problem at hand is really that there are just way too many requests (well over 100+ at a time) being sent to both parts of the website.

### Please make sure you can reproduce the bug. It's also helpful to include screenshots or animated gifs of the problem.
Here's the screenshots provided of the requests.
![Screenshot 2024-08-07 6 26 28 PM](https://github.com/user-attachments/assets/decf09a0-4e56-4b73-bf69-f696dbbd79cf)
![Screenshot 2024-08-07 6 27 58 PM](https://github.com/user-attachments/assets/d15b682e-1a1d-494c-9095-21de8e1d2221)
Someone fetched these for me.

### Steps to Reproduce
Prevent the ScratchDB server or the main website server from sending out too many requests by limiting the number of them to only 1 or 2 requests a minute (to slow down how many are getting pushed through several different domains across the Scratch website), that way, the servers will not overload and the website will perform better.

### Explain what someone needs to do in order to see what's described above. The 
more detailed and explicit the steps are the better.
I've explained pretty much in detail and explicit results, except that the website is at risk for high maintenance rundown of the website if these requests are not handled properly. This could be bad for practically almost not most, but all things on there.

### Operating System and Browser

ChromeOS 14541.0.0, Chrome 126.0.0.0.

**Comment by PaperMarioFan-2022** [comment]
Also, don't be afraid to let me know if I need to change the OP for this issue anytime. Thanks!

**Comment by ajskateboarder** [comment]
I don't think this is the place for these types of issues - you might want to keep it limited to a suggestion in the discussion forums since this is more for bugs with the site. Also, Scratch isn't regularly checking issues here

**Comment by PaperMarioFan-2022** [comment]
> I don't think this is the place for these types of issues - you might want to keep it limited to a suggestion in the discussion forums since this is more for bugs with the site. Also, Scratch isn't regularly checking issues here

Oh, I didn't notice. Thank you for pointing that out, I'll close this!
