### ISSUE TITLE
Opening any scratch team members profile will cause "scratch team is working on this" screen (and has for 12+ hours)

### ISSUE THREAD

**Issue by WoodwardIII-HS** [scratchfoundation/scratch-www#8879]
### Expected Behavior

Should open profile pages

### Actual Behavior

The page just goes to a crash screen with no explanation.

### Steps to Reproduce

1. Go to 'https://scratch.mit.edu/users/ScratchCat/'

### System Details
Mac OS 15.1 Firefox 131.0.3 (aarch64)
In addition, it's also reproducible in Chrome 130.0.6723.92 (Official Build) (arm64)

### Note
It's probably just routine server maintenance, but there's no transparency on the site as to what's going on.

**Screenshots**
![Image 11-1-24 at 10 18 PM](https://github.com/user-attachments/assets/182a6a66-22e6-4652-a7f7-13e2ad49125b)
![Image 11-2-24 at 8 43 AM](https://github.com/user-attachments/assets/8ea643ea-8584-41d2-b88d-508785783e9f)
![Image 11-1-24 at 10 30 PM](https://github.com/user-attachments/assets/28505adf-3cda-4554-9851-0108af7a939a)

**Comment by WoodwardIII-HS** [comment]
Got fixed

**Comment by EiJackGH** [comment]
I fixed

**Comment by aidasofialily-cmd** [comment]
I fixed it
